package tarea1;

import java.awt.List;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Mansilla
 */
public class Interfaz extends javax.swing.JFrame {
    //Proabando Commit
    /**
     * Creates new form Fecha
     */
    public Interfaz() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDate = new javax.swing.JFormattedTextField();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jSalidaDia = new javax.swing.JLabel();
        jPrimo = new javax.swing.JFormattedTextField();
        jCalcular = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jCombo = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jDate.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("dd/MM/yyyy"))));
        jDate.setInputVerifier(jDate.getInputVerifier());

        jButton1.setText("Aceptar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setText("dd/mm/yyyy");

        jPrimo.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));

        jCalcular.setText("Aceptar");
        jCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCalcularActionPerformed(evt);
            }
        });

        jLabel2.setText("Numero");

        jCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jDate, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                            .addComponent(jSalidaDia, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addComponent(jButton1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 107, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jPrimo, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jCalcular)
                        .addGap(72, 72, 72))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jDate, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPrimo, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jCalcular))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jSalidaDia, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
                    .addComponent(jCombo))
                .addGap(109, 109, 109))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String fecha = this.jDate.getText();
        System.out.println(fecha);
        String separ[] = fecha.split("/");
        int dia = Integer.parseInt(separ[0]);
        int mes = Integer.parseInt(separ[1]);
        int anio = Integer.parseInt(separ[2]);
        
        if(anio>=1700 && anio<=999999 ){
             if(mes<=2){        

            mes = mes + 12;
            anio = anio -1;                    
             }
                     
        //Transformacion Juliana
        int a = (int) (anio/100) ;
        System.out.println(a);
        int b = 2-a+(int)(a/4);
        System.out.println(b);
        double dataJuliana = (double) ((int)((365.25*(anio+4716)))+((int)(30.6001*(mes+1)))+dia+b-1524.5);
    
        System.out.println(dataJuliana);
        
        //Sumar para 350 para garantizar por todos los ciclos al menos una vez
        dataJuliana = dataJuliana+350;
        
        //Fecha Juliana modificada, concentrar el numero en un intervalo mas cercano
        if(dataJuliana > 5373120){
            int g=0;
            while(true){
                if(dataJuliana - 350*g*1000 >= 4278035 ){
                     System.out.println("Ciclo 0, "+ "Iteracion " + " g = " + g + " = " + (dataJuliana - 350*g*1000));
                    g++;
                }else{
                    g--;                           
                    dataJuliana = (double) (dataJuliana - 350*g*1000 );
                    break;
                }
            }
        }
        if(dataJuliana > 4278035){
            dataJuliana = dataJuliana-350*5000;
        }
        if(dataJuliana > 3912515){
            dataJuliana = dataJuliana-350*3500;
        }
        if(dataJuliana > 2687864){
            dataJuliana = dataJuliana-350*500;
        }
        
        System.out.println(dataJuliana);
        
        int contador=4;
        //donde 0 es lunes 
        //donde 1 es martes
        //donde 2 es miercoles
        //se empieza en viernes porque empezamos el 1 de Enero de 1700
        //Asi susesivamente hasta llegar a al dia Juliano
        
        int y=0;
        int q=0;
        int r=0;
        
        // 2341973 es el 1 de Enero de 1700 
        //Nos acercamos sumano multiplos de 7 para quedarnos siempre con viernes
        
        //+7^n
        while(2341973+( Math.pow(7, y))<=dataJuliana ){
             System.out.println("Ciclo 1, "+ "Iteracion " + " y = " + y + " = " + (2341973+( Math.pow(7, y-1))));
            y++;
           
        }
        
        q=y-1;
        
        int inicio = 0;
        
        //+n^n*7
        while(2341973+( Math.pow(7, q))+Math.pow(r, r)*7<=dataJuliana ){
            System.out.println("Ciclo 2, " +"Iteracion " + " r= " + r + " = " + (2341973+( Math.pow(7, q))+Math.pow(r, r-1)*7));
            r++;
           
        }
        
        inicio = (int) (2341973+( Math.pow(7, q))+Math.pow((r-1), (r-1))*7);
        
        //+n*7*10 
        int z=0;
         while(inicio+(7*z*10)<=dataJuliana ){
            System.out.println("Ciclo 3, " +"Iteracion " + " z= " + z + " = " + (-7+inicio+7*z));
            z++;                   
        } 
      
        int fin = inicio+(7*z*10)-70;
        int w=0;
        while(fin+(7*w)<=dataJuliana){
            System.out.println("Ciclo 3, " +"Iteracion " + " z= " + z + " = " + (fin+(7*w)-7));
            w++;  
        }
        
        for(int x=fin+(7*w)-7 ; x<=dataJuliana; x++){
            contador++;
            
            if(contador==7){
                contador=0;
            }          
            System.out.println("x," + x + " = " + contador);            
        }
        
        switch(contador){
            case 0:
               jSalidaDia.setText("Lunes");
               break;
            case 1:
               jSalidaDia.setText("Martes");
                break;
            case 2:
               jSalidaDia.setText("Miercoles");
                break;
            case 3:
               jSalidaDia.setText("Jueves");
                break;
            case 4:
               jSalidaDia.setText("Viernes");
                break;
            case 5:
               jSalidaDia.setText("Sabado");
                break;
            case 6:
               jSalidaDia.setText("Domingo");
                break;
        }
        jSalidaDia.updateUI();
        
        }else{
             JOptionPane.showMessageDialog(null, "año debe ser mayor o igual 1700 o menor o igual 999999");
        }
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCalcularActionPerformed
        this.jCombo.removeAllItems();
        int n = Integer.parseInt(this.jPrimo.getText());
		int tope = (int) Math.floor(Math.sqrt(n)) + 1;

		ArrayList<Long> compuestos = new ArrayList<>();
		int pos = 0;
		for (int i = 2; i <= tope; i++) {
			if (!compuestos.contains(Long.valueOf(i))) {
				for (int j = i; j <= n / i + 1; j++)
					compuestos.add(Long.valueOf(i * j));
			}
		}

		int c = 0;
		for (pos = 2; pos < n; pos++) {
			if (!compuestos.contains(Long.valueOf(pos)))
                            this.jCombo.addItem(String.valueOf(pos));
		}	
    }//GEN-LAST:event_jCalcularActionPerformed

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interfaz().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jCalcular;
    private javax.swing.JComboBox<String> jCombo;
    private javax.swing.JFormattedTextField jDate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JFormattedTextField jPrimo;
    private javax.swing.JLabel jSalidaDia;
    // End of variables declaration//GEN-END:variables
}
